#!/bin/bash
# ============================================================================
# generate-active-projects.sh
# Scans ~/.claude/projects/ for recently-touched project transcripts and writes
# the "active projects" list into CLAUDE.md between marker comments.
#
# Active = newest *.jsonl transcript mtime within 30 days.
# Usage: ./scripts/generate-active-projects.sh
#        (schedule via launchd weekly — see inline docs at bottom)
# ============================================================================

set -euo pipefail

CLAUDE_MD="${CLAUDE_MD:-$HOME/code/github/claude-config/CLAUDE.md}"
PROJECTS_DIR="$HOME/.claude/projects"
DAYS=${DAYS:-30}
START_MARKER='<!-- ACTIVE PROJECTS AUTO -->'
END_MARKER='<!-- /ACTIVE PROJECTS AUTO -->'

[ ! -f "$CLAUDE_MD" ] && { echo "error: $CLAUDE_MD not found" >&2; exit 1; }
[ ! -d "$PROJECTS_DIR" ] && { echo "error: $PROJECTS_DIR not found" >&2; exit 1; }

# Collect project dirs whose newest *.jsonl is within $DAYS days.
# Project dir names are path-encoded (e.g. "-Users-youruser-code-github-foo").
# Map back to a short repo name by taking the last hyphen-segment.
NOW=$(date +%s)
CUTOFF=$((DAYS * 86400))

declare -a ACTIVE=()
for d in "$PROJECTS_DIR"/*/; do
  [ ! -d "$d" ] && continue
  newest=$(find "$d" -maxdepth 1 -name '*.jsonl' -type f 2>/dev/null | while read -r f; do
    stat -f "%m %N" "$f" 2>/dev/null || stat -c "%Y %n" "$f" 2>/dev/null
  done | sort -rn | head -1)
  [ -z "$newest" ] && continue
  mt=$(echo "$newest" | awk '{print $1}')
  age=$((NOW - mt))
  [ "$age" -gt "$CUTOFF" ] && continue

  # Extract short repo name: dir is "-Users-youruser-code-github-<name>"
  # Take everything after the last "-github-".
  bname=$(basename "$d")
  short=${bname##*-github-}
  [ -z "$short" ] && short="$bname"

  # Skip garbage entries: path-encoded stubs (contain "-Users" in the "name"),
  # single dash (root launch), anything not looking like a real repo name.
  case "$short" in
    "-"|"--"|*"-Users"*|*"youruser"*) continue ;;
  esac
  [[ ! "$short" =~ ^[a-zA-Z0-9._-]+$ ]] && continue

  # Age in days for display
  days_ago=$((age / 86400))
  ACTIVE+=("${short}|${days_ago}")
done

# Sort by days ago (ascending) then unique by name
BLOCK=$(printf '%s\n' "${ACTIVE[@]}" | sort -t'|' -k2n | awk -F'|' '!seen[$1]++ {printf "- **%s** — %d day(s) ago\n", $1, $2}')

if [ -z "$BLOCK" ]; then
  BLOCK="- (no active projects in the last $DAYS days)"
fi

# Generate the replacement block
GENERATED=$(cat <<EOF
$START_MARKER
<!-- auto-generated by scripts/generate-active-projects.sh on $(date +%Y-%m-%d) -->
$BLOCK
$END_MARKER
EOF
)

# Replace between markers; if markers absent, append at end.
if grep -q "$START_MARKER" "$CLAUDE_MD"; then
  # Write the replacement block to a temp file and slurp it in awk — avoids
  # BSD awk's limitation that -v variables can't contain newlines.
  REPL_FILE=$(mktemp)
  printf '%s\n' "$GENERATED" > "$REPL_FILE"

  awk -v start="$START_MARKER" -v end="$END_MARKER" -v replfile="$REPL_FILE" '
    BEGIN {
      inblock = 0
      while ((getline line < replfile) > 0) {
        repl[++n] = line
      }
      close(replfile)
    }
    $0 == start {
      for (i = 1; i <= n; i++) print repl[i]
      inblock = 1
      next
    }
    $0 == end { inblock = 0; next }
    !inblock { print }
  ' "$CLAUDE_MD" > "$CLAUDE_MD.tmp" && mv "$CLAUDE_MD.tmp" "$CLAUDE_MD"
  rm -f "$REPL_FILE"
  echo "updated active projects block in $CLAUDE_MD"
else
  {
    echo ""
    echo "## Active Projects"
    echo ""
    echo "$GENERATED"
  } >> "$CLAUDE_MD"
  echo "appended active projects block to $CLAUDE_MD (markers were missing)"
fi

# ----------------------------------------------------------------------------
# To schedule weekly via launchd, drop this into ~/Library/LaunchAgents/
# com.youruser.claude.active-projects.plist and `launchctl load` it:
#
# <?xml version="1.0" encoding="UTF-8"?>
# <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
# <plist version="1.0"><dict>
#   <key>Label</key><string>com.youruser.claude.active-projects</string>
#   <key>ProgramArguments</key>
#     <array>
#       <string>/bin/bash</string>
#       <string>$HOME/code/github/claude-config/scripts/generate-active-projects.sh</string>
#     </array>
#   <key>StartCalendarInterval</key>
#     <dict><key>Weekday</key><integer>1</integer><key>Hour</key><integer>9</integer></dict>
#   <key>StandardOutPath</key><string>/tmp/claude-active-projects.log</string>
#   <key>StandardErrorPath</key><string>/tmp/claude-active-projects.log</string>
# </dict></plist>
# ----------------------------------------------------------------------------
