#!/bin/bash
# ============================================================================
# Generate ROUTING.md from installed skills, agents, and plugins
# Run by claude-config-sync.sh after deploying skills/agents
# Output: ~/.claude/ROUTING.md (auto-generated, never edit manually)
# ============================================================================

OUTFILE="$HOME/.claude/ROUTING.md"
SKILLS_DIR="$HOME/.claude/skills"
AGENTS_DIR="$HOME/.claude/agents"
PLUGINS_DIR="$HOME/.claude/plugins/cache"

cat > "$OUTFILE" << 'HEADER'
<!-- AUTO-GENERATED by generate-routing.sh — do not edit manually -->
<!-- Regenerated on each /my-claude-config-sync run -->

# Routing — Skills, Agents & Plugins

**MANDATORY:** Before starting ANY task, scan this table. If a match exists, invoke the skill/agent BEFORE writing code or responding. "I can do it without the skill" is NOT a valid reason to skip.

**Announce:** When invoking a skill or dispatching an agent from this table, always print:
`⚡ ClaudeForge: Using /skill-name for [purpose]` or `⚡ ClaudeForge: Dispatching agent-name for [purpose]`

## Skills
| Skill | When to use |
|-------|-------------|
HEADER

# Skills — read description from frontmatter
if [ -d "$SKILLS_DIR" ]; then
  for skill_dir in "$SKILLS_DIR"/*/; do
    # Handle both SKILL.md and skill.md
    skill_file="$skill_dir/SKILL.md"
    [ -f "$skill_file" ] || skill_file="$skill_dir/skill.md"
    [ -f "$skill_file" ] || continue
    name=$(basename "$skill_dir")
    desc=$(sed -n '/^description:/{ s/^description: *//; p; q; }' "$skill_file")
    [ -z "$desc" ] && continue
    desc="${desc:0:120}"
    printf "| \`/%s\` | %s |\n" "$name" "$desc" >> "$OUTFILE"
  done
fi

# Plugin skills — deduplicate by plugin:skill (multiple versions may exist)
if [ -d "$PLUGINS_DIR" ]; then
  declare -A seen_plugins
  find "$PLUGINS_DIR" -path '*/skills/*/SKILL.md' -type f 2>/dev/null | sort -r | while read -r skill_file; do
    plugin=$(echo "$skill_file" | sed -E 's|.*/cache/[^/]+/([^/]+)/.*|\1|')
    skill_name=$(basename "$(dirname "$skill_file")")
    key="${plugin}:${skill_name}"
    # Skip if already seen (sort -r ensures latest version first)
    grep -q "^| \`/${key}\`" "$OUTFILE" 2>/dev/null && continue
    desc=$(sed -n '/^description:/{ s/^description: *//; p; q; }' "$skill_file")
    [ -z "$desc" ] && continue
    desc="${desc:0:120}"
    printf "| \`/%s\` | %s |\n" "$key" "$desc" >> "$OUTFILE"
  done
fi

cat >> "$OUTFILE" << 'AGENTS_HEADER'

## Agents
| Agent | Model | When to dispatch |
|-------|-------|-----------------|
AGENTS_HEADER

# Agents — extract model from "Recommended model:" comment or known mappings
if [ -d "$AGENTS_DIR" ]; then
  find "$AGENTS_DIR" -name '*.md' -not -name 'README.md' -type f 2>/dev/null | sort | while read -r agent_file; do
    rel=$(echo "$agent_file" | sed "s|$AGENTS_DIR/||")
    # Extract description from <!-- Description: ... --> comment, fall back to first content line
    desc=$(grep -o '<!-- Description: .*-->' "$agent_file" 2>/dev/null | sed 's/<!-- Description: //; s/ -->//' | head -1)
    if [ -z "$desc" ]; then
      desc=$(sed -n '/^---$/,/^---$/d; /^$/d; /^#/d; /^<!--/d; /^##/d; p' "$agent_file" 2>/dev/null | head -1)
    fi
    [ -z "$desc" ] && continue
    # Detect model from "Recommended model:" line
    model_line=$(grep -i 'recommended model\|model.*tier\|use.*model' "$agent_file" 2>/dev/null | head -1)
    model="sonnet"
    if echo "$model_line" | grep -qi 'opus'; then
      model="opus"
    elif echo "$model_line" | grep -qi 'haiku'; then
      model="haiku"
    fi
    desc="${desc:0:100}"
    printf "| \`%s\` | %s | %s |\n" "$rel" "$model" "$desc" >> "$OUTFILE"
  done
fi

# Count entries (exclude header rows)
skill_count=$(grep -c '^| `/' "$OUTFILE" 2>/dev/null || echo 0)
agent_count=$(grep -c '^| `[a-z]' "$OUTFILE" 2>/dev/null || echo 0)

printf "\n---\n*Generated: %s — %d skills, %d agents*\n" \
  "$(date '+%Y-%m-%d %H:%M')" "$skill_count" "$agent_count" >> "$OUTFILE"

echo "ROUTING.md generated: $skill_count skills, $agent_count agents"
